// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCETKFruOo1_c02XXrjYob28U28XKHfeDg',
    appId: '1:801681056035:web:5e3238babc98ac4406ac96',
    messagingSenderId: '801681056035',
    projectId: 'serious-gaming-platform',
    authDomain: 'serious-gaming-platform.firebaseapp.com',
    databaseURL: 'https://serious-gaming-platform.firebaseio.com',
    storageBucket: 'serious-gaming-platform.appspot.com',
    measurementId: 'G-3Z6BK0XCSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsgtL3Z3LeyjghQQ0zuc-MV3dvDgSWqbc',
    appId: '1:801681056035:android:99babfd2b98ae24706ac96',
    messagingSenderId: '801681056035',
    projectId: 'serious-gaming-platform',
    databaseURL: 'https://serious-gaming-platform.firebaseio.com',
    storageBucket: 'serious-gaming-platform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3H-LKzIy7ySkPQJTOyYkljilNFlnaEEM',
    appId: '1:801681056035:ios:0a6b3216c85de67906ac96',
    messagingSenderId: '801681056035',
    projectId: 'serious-gaming-platform',
    databaseURL: 'https://serious-gaming-platform.firebaseio.com',
    storageBucket: 'serious-gaming-platform.appspot.com',
    androidClientId: '801681056035-ac531t8di00amb4fdvdnodd3l00k8q04.apps.googleusercontent.com',
    iosClientId: '801681056035-cdv0vtkagq6de5qs6k8okuo56l6s30pl.apps.googleusercontent.com',
    iosBundleId: 'nl.nbdbiblion.seriousnbd',
  );
}
